-- Generated from data/menu.js and data/sales.js. Safe to run more than once.

insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170273','سادو اثيوبيا حار','اثيوبيا من منطقة سيدامو بسلالة هيرلوم إيحاءات فاكهية (التوت الأزرق- الفراولة- العنب) معالجة مجففة - الارتفاع 2000 متر','pourover',18,null,true,false,0) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('192502','بينسا اثيوبيا حار','قهوة اثيوبية','pourover',20,null,true,false,1) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('192998','بيرياس بيرو حار','قهوة مختصة من بيرو','pourover',18,null,true,false,2) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('xmrqz5hni2k1','لاهرموسا كولومبيا حار','قهوة مختصة كولومبية','pourover',20,null,true,false,3) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('xmrqz7bp85ct','وهاج اثيوبيا حار','قهوة مختصة إثيوبية','pourover',18,null,true,false,4) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('xmqvhwyx556j','كولد برو','قهوة مقطّرة على البارد بتركيز عالي','cold-v60',24,null,true,false,5) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170309','كوكيز فانيليا','كوكيز مع رقائق الشوكلاته البلجيكية الفاخرة','bakery',10,null,true,false,6) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('193000','كوكيز شوكلت','كوكيز Dark شوكلاته بلجيكية','bakery',10,null,true,false,7) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170311','ماتيلدا كيك شوكلاته','ماتيلدا كيك شوكلاته بلجيكية','bakery',20,null,true,false,8) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170310','كوكنت مانجو','كيك مع صوص المانجو وجوز الهند','bakery',20,null,true,false,9) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170315','تشيز كيك مانجو','مكونات التشيز كيك مضاف إليها طبقة صوص المانجو','bakery',20,null,true,false,10) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170313','تراميسو','طبقة بسكوت فاخرة (ليدي فنجر) مشربة بالقهوة ومضاف إليها كريمة وطبقة من بودرة الكاكاو','bakery',20,null,true,false,11) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('201080','سينابون كلاسيك','لفائف القرفة','bakery',16,null,true,false,12) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('xmqvitfx45ss','تشيز توت أزرق','مكونات التشيز كيك مضاف إليها طبقة صوص التوت','bakery',22,null,true,false,13) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('dessert-red-berry-cheesecake','تشيز توت أحمر','تشيز كيك بطبقة صوص التوت الأحمر','bakery',22,null,true,false,14) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('180992','إسبريسو','إسبريسو من حبوب مختصة فاخرة','espresso',12,null,true,false,15) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170279','أمريكانو حار','قهوة سوداء','hot',14,null,true,false,16) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170283','لاتيه حار','دبل اسبريسو - حليب','hot',17,null,true,false,17) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170284','سبانش لاتيه حار','دبل اسبريسو - وصفة الاسبانيش الخاصة','hot',18,null,true,false,18) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('hot-saudi-coffee','قهوة سعودية','قهوة سعودية تقليدية','hot',12,null,true,false,19) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170292','آيس أمريكانو','قهوة سوداء','cold',14,null,true,false,20) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170293','لاتيه بارد','دبل اسبريسو مع حليب','cold',17,null,true,false,21) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170294','سبانش لاتيه بارد','دبل اسبريسو مع وصفة الاسبانيش الخاصة','cold',18,null,true,false,22) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170298','آيس لاتيه كراميل','إسبريسو وحليب بنكهة الكراميل','cold',18,null,true,false,23) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170299','آيس شوكلت','حليب بالشوكلاته البلجيكية','cold',18,null,true,false,24) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('cold-rose-milk','حليب روز','مشروب أطفال بالحليب ونكهة الروز','cold',5,null,true,false,25) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170300','ماتشا كلاسيك','أجود أنواع الماتشا اليابانية بدون إضافات إختيارات الحليب ( صويا، كوكنت، لوز، حليب بقري ) إختيارات إضافية: (فانيليا، كارميل ) 4 SR','matcha',22,null,true,false,26) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170302','ماتشا لافندر','أجود أنواع الماتشا اليابانية مع نكهة اللافندر و حليب الكوكنت .','matcha',22,null,true,false,27) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('171003','ماتشا توت','أجود أنواع الماتشا اليابانية بنكهة التوت وحليب الصويا ويتم تزيينها بقطع التوت المجفف بالتبريد.','matcha',22,null,true,false,28) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('xmrqxmk1p6dm','ماتشا فانيليا','توازن مثالي بين الماتشا اليابانية الفاخرة والفانيليا الطبيعية','matcha',22,null,true,false,29) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('xmrqy33hc4ym','ماتشا كوكنت','توازن مثالي بين الماتشا اليابانية وجوز الهند الكريمي','matcha',22,null,true,false,30) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;
insert into public.products (id,name,description,section_id,price,size_prices,is_active,sold_out,sort_order) values ('170305','كركديه كلاسيك','كركديه طبيعي منعش','hibiscus',16,null,true,false,31) on conflict (id) do update set name=excluded.name,description=excluded.description,section_id=excluded.section_id,price=excluded.price,size_prices=excluded.size_prices,sort_order=excluded.sort_order;

insert into public.offers (id,name,description,image_url,price,original_price,parts,is_active,sort_order) values ('c1','بداية اليوم','لاتيه حار + كوكيز فانيليا','assets/img/offers/combo-start-day.webp',23,27,'["لاتيه حار","كوكيز فانيليا"]'::jsonb,true,0) on conflict (id) do update set name=excluded.name,description=excluded.description,image_url=excluded.image_url,price=excluded.price,original_price=excluded.original_price,parts=excluded.parts,sort_order=excluded.sort_order;
insert into public.offers (id,name,description,image_url,price,original_price,parts,is_active,sort_order) values ('c2','بريك الشغل','سبانش لاتيه بارد + كوكيز شوكلت','assets/img/offers/combo-work-break.webp',24,28,'["سبانش لاتيه بارد","كوكيز شوكلت"]'::jsonb,true,1) on conflict (id) do update set name=excluded.name,description=excluded.description,image_url=excluded.image_url,price=excluded.price,original_price=excluded.original_price,parts=excluded.parts,sort_order=excluded.sort_order;
insert into public.offers (id,name,description,image_url,price,original_price,parts,is_active,sort_order) values ('c3','تجربة المختصة','سادو اثيوبيا حار + ماتيلدا كيك شوكلاته','assets/img/offers/combo-specialty.webp',34,38,'["سادو اثيوبيا حار","ماتيلدا كيك شوكلاته"]'::jsonb,true,2) on conflict (id) do update set name=excluded.name,description=excluded.description,image_url=excluded.image_url,price=excluded.price,original_price=excluded.original_price,parts=excluded.parts,sort_order=excluded.sort_order;
insert into public.offers (id,name,description,image_url,price,original_price,parts,is_active,sort_order) values ('c4','قعدة اثنين','٢ سبانش لاتيه حار + تراميسو','assets/img/offers/combo-for-two.webp',50,56,'["سبانش لاتيه حار","سبانش لاتيه حار","تراميسو"]'::jsonb,true,3) on conflict (id) do update set name=excluded.name,description=excluded.description,image_url=excluded.image_url,price=excluded.price,original_price=excluded.original_price,parts=excluded.parts,sort_order=excluded.sort_order;

insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_hot_0','hot','شوت إسبريسو زيادة',4,true,0) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_hot_1','hot','حليب نباتي (لوز/شوفان)',5,true,1) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_hot_2','hot','سيرب (كراميل/فانيليا)',3,true,2) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_hot_3','hot','كوكيز فانيليا جنب القهوة',10,true,3) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_cold_0','cold','شوت إسبريسو زيادة',4,true,0) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_cold_1','cold','حليب نباتي (لوز/شوفان)',5,true,1) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_cold_2','cold','سيرب (كراميل/فانيليا)',3,true,2) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_pourover_0','pourover','ماء فوار جانبي',3,true,0) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_pourover_1','pourover','كوكيز فانيليا جنب القهوة',10,true,1) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_cold-v60_0','cold-v60','ماء فوار جانبي',3,true,0) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_cold-v60_1','cold-v60','كوكيز فانيليا جنب القهوة',10,true,1) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_bakery_0','bakery','صوص شوكولاتة',3,true,0) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon_bakery_1','bakery','كريمة',3,true,1) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon__default_0','_default','كوكيز فانيليا',10,true,0) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;
insert into public.addons (id,section_id,name,price,is_active,sort_order) values ('addon__default_1','_default','كوكيز شوكلت',10,true,1) on conflict (id) do update set section_id=excluded.section_id,name=excluded.name,price=excluded.price,sort_order=excluded.sort_order;

insert into public.store_settings (id,tables_count,ordering_open) values (1,10,true) on conflict (id) do update set tables_count=excluded.tables_count;
